export const SEED_DATA = {
  communityCategories: [
    { id: 1, name: 'Olahraga', description: 'Komunitas berbasis aktivitas fisik dan olahraga' },
    { id: 2, name: 'Seni & Budaya', description: 'Komunitas seni, musik, dan budaya lokal' },
    { id: 3, name: 'Bisnis & Profesional', description: 'Komunitas networking dan pengembangan karir' },
    { id: 4, name: 'Teknologi', description: 'Komunitas tech enthusiast dan developer' },
  ],

  eventCategories: [
    { id: 1, name: 'Workshop', description: 'Pelatihan dan pembelajaran praktis' },
    { id: 2, name: 'Turnamen', description: 'Kompetisi antar anggota komunitas' },
    { id: 3, name: 'Gathering', description: 'Acara kumpul dan networking' },
    { id: 4, name: 'Seminar', description: 'Presentasi dan diskusi topik tertentu' },
  ],

  venues: [
    { id: 1, name: "D'Paragon Jaksel", address: 'Jl. Fatmawati Raya No. 20, Jakarta Selatan', capacity: 200, city: 'Jakarta', maps_link: null },
    { id: 2, name: "D'Paragon BSD City", address: 'BSD City, Tangerang Selatan', capacity: 150, city: 'Jakarta', maps_link: null },
    { id: 3, name: 'GOR Senayan', address: 'Jl. Pintu Satu Senayan, Jakarta Pusat', capacity: 500, city: 'Jakarta', maps_link: null },
    { id: 4, name: 'Gedung Serbaguna BSD', address: 'Jl. Pahlawan Seribu, BSD City', capacity: 300, city: 'Jakarta', maps_link: null },
    { id: 5, name: "D'Paragon Semarang", address: 'Jl. Pandanaran No. 5, Semarang', capacity: 180, city: 'Semarang', maps_link: null },
    { id: 6, name: "D'Paragon Malang", address: 'Jl. Ijen Boulevard No. 10, Malang', capacity: 160, city: 'Malang', maps_link: null },
    { id: 7, name: "D'Paragon Yogyakarta", address: 'Jl. Magelang Km. 4, Yogyakarta', capacity: 170, city: 'Yogyakarta', maps_link: null },
    { id: 8, name: "D'Paragon Surabaya", address: 'Jl. HR Muhammad No. 88, Surabaya', capacity: 200, city: 'Surabaya', maps_link: null },
    { id: 9, name: "D'Paragon Solo", address: 'Jl. Slamet Riyadi No. 200, Solo', capacity: 150, city: 'Solo', maps_link: null },
    { id: 10, name: "D'Paragon Banjarmasin", address: 'Jl. Ahmad Yani Km. 3, Banjarmasin', capacity: 130, city: 'Banjarmasin', maps_link: null },
    { id: 11, name: "D'Paragon Palembang", address: 'Jl. Jend. Sudirman No. 50, Palembang', capacity: 175, city: 'Palembang', maps_link: null },
  ],

  users: [
    { id: 1, name: 'Budi Santoso', email: 'budi@email.com', phone: '081234567890', city: 'Jakarta' },
    { id: 2, name: 'Siti Rahayu', email: 'siti@email.com', phone: '082345678901', city: 'Jakarta' },
    { id: 3, name: 'Ahmad Fauzi', email: 'ahmad@email.com', phone: '083456789012', city: 'Jakarta' },
    { id: 4, name: 'Dewi Lestari', email: 'dewi@email.com', phone: '084567890123', city: 'Jakarta' },
    { id: 5, name: 'Rizky Pratama', email: 'rizky@email.com', phone: '085678901234', city: 'Jakarta' },
    { id: 6, name: 'Kevin Wijaya', email: 'kevin@email.com', phone: '086789012345', city: 'Jakarta' },
    { id: 7, name: 'Fajar Nugroho', email: 'fajar@email.com', phone: '087890123456', city: 'Jakarta' },
    { id: 8, name: 'Indah Permata', email: 'indah@email.com', phone: '088901234567', city: 'Jakarta' },
    { id: 9, name: 'Hendra Kusuma', email: 'hendra@email.com', phone: '089012345678', city: 'Jakarta' },
    { id: 10, name: 'Maya Sari', email: 'maya@email.com', phone: '080123456789', city: 'Jakarta' },
    { id: 11, name: 'Rina Wahyuni', email: 'rina@email.com', phone: '081198765432', city: 'Jakarta' },
  ],

  communityMembers: [
    { id: 1, community_id: 1, user_id: 1, status: 'active' },
  ],

  communities: [
    { id: 1, name: 'Lari Pagi Community', description: "Komunitas lari pagi setiap akhir pekan di kawasan D'Paragon. Terbuka untuk semua level.", category_id: 1, type: 'Internal', city: 'Jakarta', status: 'active', wa_link: 'https://chat.whatsapp.com/xxx1', admin: 'Bima Prakoso', cover_image: '', rules: ['Datang tepat waktu', 'Hormati pace peserta lain', 'Gunakan perlengkapan olahraga yang aman'] },
    { id: 2, name: "Futsal D'Paragon", description: "Komunitas futsal rutin setiap Sabtu sore. Terbuka untuk semua penghuni.", category_id: 1, type: 'Internal', city: 'Jakarta', status: 'active', wa_link: 'https://chat.whatsapp.com/xxx2', admin: 'Raka Wijaya', cover_image: '', rules: ['Fair play', 'Konfirmasi hadir sebelum main', 'Ikuti arahan koordinator lapangan'] },
    { id: 3, name: 'Photography Club', description: "Komunitas pecinta fotografi. Rutin photo walk dan pameran karya.", category_id: 2, type: 'Internal', city: 'Jakarta', status: 'active', wa_link: 'https://chat.whatsapp.com/xxx3', admin: 'Nadia Maharani', cover_image: '', rules: ['Minta izin sebelum memotret orang', 'Jaga area hunting tetap rapi'] },
    { id: 4, name: "D'Paragon Entrepreneur", description: "Forum networking dan pengembangan bisnis antar penghuni.", category_id: 3, type: 'Eksternal', city: 'Jakarta', status: 'active', wa_link: 'https://chat.whatsapp.com/xxx4', admin: 'Alya Saputra', cover_image: '', rules: ['No hard selling tanpa izin moderator', 'Jaga kerahasiaan diskusi bisnis'] },
    { id: 5, name: 'Tech Enthusiast BSD', description: "Komunitas tech untuk developer, designer, dan tech enthusiast.", category_id: 4, type: 'Eksternal', city: 'Jakarta', status: 'inactive', wa_link: 'https://chat.whatsapp.com/xxx5', admin: null, cover_image: '', rules: [] },
    { id: 6, name: 'Komunitas Batik Semarang', description: "Komunitas pengrajin dan pecinta batik khas Semarang.", category_id: 2, type: 'Internal', city: 'Semarang', status: 'active', wa_link: 'https://chat.whatsapp.com/xxx6', admin: 'Endah Kusumawardani', cover_image: '', rules: ['Hormati karya sesama', 'Jaga kebersihan area workshop'] },
    { id: 7, name: 'Badminton Club Malang', description: "Komunitas bulu tangkis rutin di D'Paragon Malang.", category_id: 1, type: 'Internal', city: 'Malang', status: 'active', wa_link: 'https://chat.whatsapp.com/xxx7', admin: 'Adi Wibowo', cover_image: '', rules: ['Fair play', 'Konfirmasi hadir H-1'] },
    { id: 8, name: 'Komunitas Kreatif Yogyakarta', description: "Komunitas desainer, ilustrator, dan kreator konten D'Paragon Yogya.", category_id: 2, type: 'Internal', city: 'Yogyakarta', status: 'active', wa_link: 'https://chat.whatsapp.com/xxx8', admin: 'Rini Handayani', cover_image: '', rules: ['Dukung karya sesama', 'Tidak plagiarisme'] },
    { id: 9, name: 'Komunitas Olahraga Surabaya', description: "One-stop komunitas olahraga D'Paragon Surabaya.", category_id: 1, type: 'Internal', city: 'Surabaya', status: 'active', wa_link: 'https://chat.whatsapp.com/xxx9', admin: 'Yoga Pratama', cover_image: '', rules: ['Datang tepat waktu', 'Pakai pakaian olahraga'] },
    { id: 10, name: 'Komunitas Budaya Solo', description: "Melestarikan kesenian tradisional Solo di lingkungan D'Paragon.", category_id: 2, type: 'Eksternal', city: 'Solo', status: 'active', wa_link: 'https://chat.whatsapp.com/xxx10', admin: 'Sri Mulyani', cover_image: '', rules: ['Hormati nilai tradisional', 'Hadir rutin untuk menjaga kualitas latihan'] },
    { id: 11, name: 'Komunitas UMKM Banjarmasin', description: "Komunitas pelaku UMKM D'Paragon Banjarmasin, fokus digitalisasi usaha.", category_id: 3, type: 'Eksternal', city: 'Banjarmasin', status: 'active', wa_link: 'https://chat.whatsapp.com/xxx11', admin: 'Hendra Kusuma', cover_image: '', rules: ['Saling support usaha sesama anggota'] },
    { id: 12, name: "D'Paragon Tech Palembang", description: "Komunitas teknologi dan startup D'Paragon Palembang.", category_id: 4, type: 'Eksternal', city: 'Palembang', status: 'active', wa_link: 'https://chat.whatsapp.com/xxx12', admin: 'Rizki Andika', cover_image: '', rules: ['Share ilmu secara terbuka', 'Tidak diskriminasi level skill'] },
    { id: 13, name: 'Lari Pagi Semarang', description: "Komunitas lari santai di sekitar kawasan D'Paragon Semarang.", category_id: 1, type: 'Internal', city: 'Semarang', status: 'active', wa_link: '#', admin: 'Dwi Santoso', cover_image: '', rules: ['Datang tepat waktu', 'Saling menyemangati'] },
    { id: 14, name: 'Komunitas Kuliner Malang', description: "Pecinta kuliner khas Malang berkumpul! Rutin food tour.", category_id: 2, type: 'Eksternal', city: 'Malang', status: 'active', wa_link: '#', admin: 'Sari Wijayanti', cover_image: '', rules: ['Respek pemilik warung', 'Review jujur dan sopan'] },
    { id: 15, name: "D'Paragon Entrepreneur Yogyakarta", description: "Forum bisnis dan networking penghuni D'Paragon Yogyakarta.", category_id: 3, type: 'Eksternal', city: 'Yogyakarta', status: 'active', wa_link: '#', admin: 'Bagas Prasetya', cover_image: '', rules: ['No hard selling tanpa izin', 'Aktif berpartisipasi'] },
    { id: 16, name: 'Coffee Lovers Surabaya', description: "Komunitas pencinta kopi specialty di D'Paragon Surabaya.", category_id: 2, type: 'Internal', city: 'Surabaya', status: 'active', wa_link: '#', admin: 'Tino Hermawan', cover_image: '', rules: ['Hormati preferensi rasa orang lain'] },
    { id: 17, name: 'Chess Club Solo', description: "Komunitas catur D'Paragon Solo untuk semua kalangan.", category_id: 4, type: 'Internal', city: 'Solo', status: 'active', wa_link: '#', admin: 'Joko Santoso', cover_image: '', rules: ['Hormati lawan', 'Tidak menggunakan engine/alat bantu'] },
    { id: 18, name: 'Komunitas Wisata Lokal Banjarmasin', description: "Jelajahi keindahan Banjarmasin bersama!", category_id: 2, type: 'Internal', city: 'Banjarmasin', status: 'active', wa_link: '#', admin: 'Laila Sari', cover_image: '', rules: ['Tepat waktu saat trip', 'Jaga kebersihan tempat wisata'] },
    { id: 19, name: 'Komunitas Kuliner Palembang', description: "Pempek, tekwan, mie celor — komunitas kuliner D'Paragon Palembang.", category_id: 2, type: 'Internal', city: 'Palembang', status: 'active', wa_link: '#', admin: 'Dewi Fitriani', cover_image: '', rules: ['Appreciate semua jenis kuliner', 'Support warung lokal'] },
  ],

  organizers: [
    { id: 1, name: 'Lari Pagi Community', description: 'Komunitas lari pagi D\'Paragon', email: null, phone: null, website: null, pic: null, status: 'active', notes: null, submitted_at: null },
    { id: 2, name: "Futsal D'Paragon", description: 'Komunitas futsal D\'Paragon', email: null, phone: null, website: null, pic: null, status: 'active', notes: null, submitted_at: null },
    { id: 3, name: "D'Paragon Community Team", description: 'Tim komunitas internal D\'Paragon', email: null, phone: null, website: null, pic: null, status: 'active', notes: null, submitted_at: null },
    { id: 4, name: "D'Paragon Entrepreneur", description: 'Forum bisnis D\'Paragon', email: null, phone: null, website: null, pic: null, status: 'active', notes: null, submitted_at: null },
    { id: 5, name: 'Badminton Club Malang', email: null, phone: null, website: null, pic: null, status: 'active', notes: null, submitted_at: null },
    { id: 6, name: 'Urban Active', description: 'EO wellness events', email: 'dimas@urbanactive.id', phone: '081333445566', website: null, pic: 'Dimas Putra', status: 'pending', notes: 'Co-host wellness day di DParagon BSD', submitted_at: '2026-04-04' },
    { id: 7, name: "D'Paragon Entrepreneur Yogya", email: null, phone: null, website: null, pic: null, status: 'active', notes: null, submitted_at: null },
    { id: 8, name: 'Coffee Lovers Surabaya', email: null, phone: null, website: null, pic: null, status: 'active', notes: null, submitted_at: null },
    { id: 9, name: 'Chess Club Solo', email: null, phone: null, website: null, pic: null, status: 'active', notes: null, submitted_at: null },
    { id: 10, name: 'Lari Pagi Semarang', email: null, phone: null, website: null, pic: null, status: 'active', notes: null, submitted_at: null },
  ],

  sponsors: [
    { id: 1, name: 'Hydro Plus', description: 'Sponsor hydration booth untuk event lari', email: 'mira@hydroplus.id', phone: '081222334455', website: null, pic: 'Mira Santoso', status: 'active', notes: null, submitted_at: '2026-04-02' },
    { id: 2, name: 'Sporta Arena', description: 'Sponsor peralatan olahraga', email: null, phone: null, website: null, pic: null, status: 'active', notes: null, submitted_at: null },
    { id: 3, name: 'ScaleUp Lab', description: 'Sponsor event bisnis', email: null, phone: null, website: null, pic: null, status: 'active', notes: null, submitted_at: null },
    { id: 4, name: 'Board Game Jakarta', description: 'Komunitas board game', email: 'lia@bgj.id', phone: '081444556677', website: null, pic: 'Lia Prameswari', status: 'pending', notes: 'Ajukan komunitas board game bulanan di area komunal', submitted_at: '2026-04-08' },
    { id: 5, name: 'Kopi Teman', description: 'Sponsor minuman gathering', email: null, phone: null, website: null, pic: null, status: 'active', notes: null, submitted_at: null },
  ],

  events: [
    { id: 1, name: "Marathon Mini D'Paragon 2026", description: "Lari bersama 5K dan 10K di kawasan D'Paragon BSD City. Terbuka untuk semua penghuni dan tamu undangan. Finisher mendapatkan medali dan merchandise eksklusif.", category_id: 2, venue_id: 2, status: 'Registration Open', start_date: '2026-08-20', end_date: '2026-08-20', start_time: '06:00', end_time: '10:00', quota: 100, price: 75000, cover_image: '', community_id: 1, facilities: ['Medali finisher', 'Kaos eksklusif peserta', 'Konsumsi & minuman', 'Dokumentasi foto profesional'], rules: ['QR ticket wajib ditunjukkan saat check-in', 'Peserta menyetujui dokumentasi foto dan video event', 'Terbuka untuk penghuni dan tamu undangan yang sudah terdaftar'] },
    { id: 2, name: 'Workshop Fotografi: Landscape & Street', description: 'Workshop intensif sehari penuh bersama fotografer profesional. Belajar komposisi dan editing.', category_id: 1, venue_id: 1, status: 'Draft', start_date: '2026-09-10', end_date: '2026-09-10', start_time: null, end_time: null, quota: 30, price: 150000, cover_image: '', community_id: 3, facilities: [], rules: [] },
    { id: 3, name: 'Turnamen Futsal Antar Komunitas', description: "Turnamen futsal berhadiah total Rp 5.000.000 untuk komunitas D'Paragon. Daftarkan timmu sekarang!", category_id: 2, venue_id: 3, status: 'Registration Open', start_date: '2026-09-24', end_date: '2026-09-25', start_time: '08:00', end_time: null, quota: 80, price: 50000, cover_image: '', community_id: 2, facilities: [], rules: ['Satu tim maksimal 8 pemain', 'Check-in dilakukan oleh kapten tim'] },
    { id: 4, name: 'Gathering Bisnis Q2 2026', description: "Networking dan sharing session komunitas bisnis D'Paragon. Tema: Scaling Your Business.", category_id: 3, venue_id: 1, status: 'Recap Pending', start_date: '2026-04-15', end_date: '2026-04-15', start_time: '19:00', end_time: null, quota: 60, price: 0, cover_image: '', community_id: 4, facilities: [], rules: [] },
    { id: 5, name: 'Seminar Investasi Properti', description: 'Seminar eksklusif tentang investasi properti bersama praktisi terkemuka.', category_id: 4, venue_id: 4, status: 'Draft', start_date: '2026-10-05', end_date: '2026-10-05', start_time: null, end_time: null, quota: 120, price: 200000, cover_image: '', community_id: null, facilities: [], rules: [] },
    { id: 6, name: "Gathering Keluarga D'Paragon", description: "Acara gathering keluarga untuk mempererat hubungan antar penghuni D'Paragon.", category_id: 3, venue_id: 1, status: 'Registration Open', start_date: '2026-09-18', end_date: '2026-09-18', start_time: '10:00', end_time: null, quota: 200, price: 0, cover_image: '', community_id: null, facilities: [], rules: ['Tunjukkan QR pass saat masuk area event', 'Anak-anak wajib dalam pendampingan orang tua'] },
    { id: 8, name: 'Gathering Bisnis Q2 2026 (Recap)', description: "Networking dan sharing session komunitas bisnis D'Paragon dengan tema Scaling Your Business. Event sudah selesai.", category_id: 3, venue_id: 1, status: 'Recap Published', start_date: '2026-04-15', end_date: '2026-04-15', start_time: '19:00', end_time: null, quota: 60, price: 0, cover_image: '', community_id: 4, facilities: [], rules: [] },
    { id: 101, name: "Workshop Batik Digital D'Paragon Semarang", description: "Pelajari seni batik modern dengan pendekatan digital bersama pengrajin batik ternama Semarang.", category_id: 1, venue_id: 5, status: 'Registration Open', start_date: '2026-10-07', end_date: '2026-10-07', start_time: '09:00', end_time: null, quota: 40, price: 100000, cover_image: '', community_id: 6, facilities: [], rules: ['QR ticket wajib saat check-in', 'Bahan habis pakai disediakan panitia'] },
    { id: 102, name: "Lari Pagi Kota Tua Semarang", description: "Fun run 5K melewati kawasan Kota Tua Semarang yang ikonik.", category_id: 2, venue_id: 5, status: 'Registration Open', start_date: '2026-10-14', end_date: '2026-10-14', start_time: '05:30', end_time: null, quota: 150, price: 50000, cover_image: '', community_id: 13, facilities: [], rules: ['QR ticket wajib saat check-in', 'Wajib mengenakan pakaian olahraga'] },
    { id: 103, name: 'Festival Kuliner Komunitas Malang', description: "Pesta kuliner khas Malang — dari bakso legendaris hingga keripik tempe.", category_id: 3, venue_id: 6, status: 'Registration Open', start_date: '2026-10-21', end_date: '2026-10-21', start_time: '10:00', end_time: null, quota: 300, price: 0, cover_image: '', community_id: 14, facilities: [], rules: ['Gratis untuk penghuni D\'Paragon', 'Bawa wadah sendiri untuk kurangi sampah'] },
    { id: 104, name: "Turnamen Bulu Tangkis D'Paragon Malang", description: "Turnamen bulu tangkis berhadiah untuk penghuni D'Paragon Malang.", category_id: 2, venue_id: 6, status: 'Registration Open', start_date: '2026-11-05', end_date: '2026-11-06', start_time: '08:00', end_time: null, quota: 64, price: 75000, cover_image: '', community_id: 7, facilities: [], rules: ['Pendaftaran per individu', 'Bawa raket sendiri'] },
    { id: 105, name: 'Seminar Properti & Investasi Yogyakarta', description: "Seminar eksklusif bersama pakar properti membahas peluang investasi di Yogyakarta.", category_id: 4, venue_id: 7, status: 'Registration Open', start_date: '2026-10-12', end_date: '2026-10-12', start_time: '14:00', end_time: null, quota: 80, price: 50000, cover_image: '', community_id: 15, facilities: [], rules: ['Konfirmasi hadir H-1', 'Dress code: smart casual'] },
    { id: 106, name: 'Gathering Komunitas Kreatif Yogyakarta', description: "Kumpul bareng para kreator, desainer, dan seniman penghuni D'Paragon Yogyakarta.", category_id: 3, venue_id: 7, status: 'Registration Open', start_date: '2026-10-28', end_date: '2026-10-28', start_time: '16:00', end_time: null, quota: 60, price: 0, cover_image: '', community_id: 8, facilities: [], rules: ['Terbuka untuk penghuni', 'Boleh bawa karya untuk dipamerkan'] },
    { id: 107, name: "D'Paragon Sports Day Surabaya", description: "Hari olahraga komunitas D'Paragon Surabaya!", category_id: 2, venue_id: 8, status: 'Registration Open', start_date: '2026-10-15', end_date: '2026-10-15', start_time: '07:00', end_time: null, quota: 200, price: 0, cover_image: '', community_id: 9, facilities: [], rules: ['Wajib daftar online sebelumnya', 'Pakai pakaian olahraga'] },
    { id: 108, name: 'Workshop Kopi & Barista Surabaya', description: "Belajar teknik brewing kopi specialty bersama barista profesional.", category_id: 1, venue_id: 8, status: 'Registration Open', start_date: '2026-11-12', end_date: '2026-11-12', start_time: '10:00', end_time: null, quota: 20, price: 150000, cover_image: '', community_id: 16, facilities: [], rules: ['Kuota sangat terbatas, daftar segera', 'Alat disediakan panitia'] },
    { id: 109, name: "Gathering Budaya Solo — Batik & Wayang", description: "Mengenal kekayaan budaya Solo bersama penghuni D'Paragon.", category_id: 3, venue_id: 9, status: 'Registration Open', start_date: '2026-10-20', end_date: '2026-10-20', start_time: '15:00', end_time: null, quota: 100, price: 0, cover_image: '', community_id: 10, facilities: [], rules: ['Gratis untuk penghuni', 'Dress code: sentuhan batik dianjurkan'] },
    { id: 110, name: "Turnamen Catur D'Paragon Solo", description: "Turnamen catur terbuka untuk penghuni D'Paragon Solo. Sistem Swiss 7 babak.", category_id: 2, venue_id: 9, status: 'Registration Open', start_date: '2026-11-04', end_date: '2026-11-04', start_time: '09:00', end_time: null, quota: 32, price: 25000, cover_image: '', community_id: 17, facilities: [], rules: ['Bawa papan catur sendiri jika punya', 'Keterlambatan > 15 menit = forfeit'] },
    { id: 111, name: 'Wisata Sungai & Pasar Terapung Banjarmasin', description: "Jelajahi keunikan Banjarmasin bersama komunitas D'Paragon!", category_id: 3, venue_id: 10, status: 'Registration Open', start_date: '2026-10-27', end_date: '2026-10-27', start_time: '06:00', end_time: null, quota: 40, price: 75000, cover_image: '', community_id: 18, facilities: [], rules: ['Wajib hadir tepat waktu', 'Transportasi speedboat disediakan'] },
    { id: 112, name: 'Workshop UMKM Digital Banjarmasin', description: "Bantu pelaku UMKM penghuni D'Paragon Banjarmasin go digital.", category_id: 1, venue_id: 10, status: 'Registration Open', start_date: '2026-11-11', end_date: '2026-11-11', start_time: '09:00', end_time: null, quota: 30, price: 0, cover_image: '', community_id: 11, facilities: [], rules: ['Bawa laptop atau smartphone', 'Gratis untuk penghuni'] },
    { id: 113, name: 'Festival Pempek & Kuliner Palembang', description: "Rayakan kekayaan kuliner Palembang bersama komunitas D'Paragon!", category_id: 3, venue_id: 11, status: 'Registration Open', start_date: '2026-10-22', end_date: '2026-10-22', start_time: '11:00', end_time: null, quota: 250, price: 0, cover_image: '', community_id: 19, facilities: [], rules: ['Gratis untuk semua penghuni', 'Datang lebih awal untuk mendapatkan tempat terbaik'] },
    { id: 114, name: 'Seminar Teknologi & Startup Palembang', description: "Sesi inspiratif bersama founder startup lokal Palembang.", category_id: 4, venue_id: 11, status: 'Registration Open', start_date: '2026-11-18', end_date: '2026-11-18', start_time: '14:00', end_time: null, quota: 100, price: 25000, cover_image: '', community_id: 12, facilities: [], rules: ['Daftar online sebelumnya', 'Dress code: business casual'] },
  ],

  eventOrganizers: [
    { event_id: 1, organizer_id: 1 },
    { event_id: 3, organizer_id: 2 },
    { event_id: 4, organizer_id: 4 },
    { event_id: 6, organizer_id: 3 },
    { event_id: 8, organizer_id: 4 },
    { event_id: 101, organizer_id: 3 },
    { event_id: 102, organizer_id: 10 },
    { event_id: 103, organizer_id: 3 },
    { event_id: 104, organizer_id: 5 },
    { event_id: 105, organizer_id: 7 },
    { event_id: 106, organizer_id: 8 },
    { event_id: 107, organizer_id: 3 },
    { event_id: 108, organizer_id: 8 },
    { event_id: 109, organizer_id: 3 },
    { event_id: 110, organizer_id: 9 },
    { event_id: 111, organizer_id: 3 },
    { event_id: 112, organizer_id: 4 },
    { event_id: 113, organizer_id: 3 },
    { event_id: 114, organizer_id: 4 },
  ],

  eventSponsors: [
    { event_id: 1, sponsor_id: 1 },
    { event_id: 3, sponsor_id: 2 },
    { event_id: 4, sponsor_id: 3 },
    { event_id: 6, sponsor_id: 5 },
    { event_id: 8, sponsor_id: 3 },
  ],

  eventAgenda: [
    { id: 1, event_id: 1, time: '06:00', activity: 'Registrasi & warm-up', order: 1 },
    { id: 2, event_id: 1, time: '06:30', activity: 'Flag off lari 5K & 10K', order: 2 },
    { id: 3, event_id: 1, time: '08:30', activity: 'Finish line & medali', order: 3 },
    { id: 4, event_id: 1, time: '09:00', activity: 'Sesi foto & doorprize', order: 4 },
  ],

  participants: [
    { id: 1, user_id: 1, name: 'Budi Santoso', email: 'budi@email.com', phone: '081234567890', event_id: 1, payment_status: 'Lunas', checkin_status: 'Belum', booked_at: '2026-03-15T00:00:00Z', price: 75000 },
    { id: 2, user_id: 2, name: 'Siti Rahayu', email: 'siti@email.com', phone: '082345678901', event_id: 1, payment_status: 'Lunas', checkin_status: 'Belum', booked_at: '2026-03-16T00:00:00Z', price: 75000 },
    { id: 3, user_id: 3, name: 'Ahmad Fauzi', email: 'ahmad@email.com', phone: '083456789012', event_id: 1, payment_status: 'Pending', checkin_status: 'Belum', booked_at: '2026-03-17T00:00:00Z', price: 75000 },
    { id: 4, user_id: 4, name: 'Dewi Lestari', email: 'dewi@email.com', phone: '084567890123', event_id: 1, payment_status: 'Lunas', checkin_status: 'Belum', booked_at: '2026-03-18T00:00:00Z', price: 75000 },
    { id: 5, user_id: 5, name: 'Rizky Pratama', email: 'rizky@email.com', phone: '085678901234', event_id: 1, payment_status: 'Lunas', checkin_status: 'Belum', booked_at: '2026-03-19T00:00:00Z', price: 75000 },
    { id: 6, user_id: 6, name: 'Kevin Wijaya', email: 'kevin@email.com', phone: '086789012345', event_id: 3, payment_status: 'Lunas', checkin_status: 'Belum', booked_at: '2026-04-01T00:00:00Z', price: 50000 },
    { id: 7, user_id: 7, name: 'Fajar Nugroho', email: 'fajar@email.com', phone: '087890123456', event_id: 3, payment_status: 'Pending', checkin_status: 'Belum', booked_at: '2026-04-02T00:00:00Z', price: 50000 },
    { id: 8, user_id: 8, name: 'Indah Permata', email: 'indah@email.com', phone: '088901234567', event_id: 3, payment_status: 'Lunas', checkin_status: 'Belum', booked_at: '2026-04-03T00:00:00Z', price: 50000 },
    { id: 9, user_id: 9, name: 'Hendra Kusuma', email: 'hendra@email.com', phone: '089012345678', event_id: 4, payment_status: 'Gratis', checkin_status: 'Sudah', booked_at: '2026-03-01T00:00:00Z', price: 0 },
    { id: 10, user_id: 10, name: 'Maya Sari', email: 'maya@email.com', phone: '080123456789', event_id: 4, payment_status: 'Gratis', checkin_status: 'Sudah', booked_at: '2026-03-02T00:00:00Z', price: 0 },
    { id: 11, user_id: 11, name: 'Rina Wahyuni', email: 'rina@email.com', phone: '081198765432', event_id: 4, payment_status: 'Gratis', checkin_status: 'Sudah', booked_at: '2026-03-03T00:00:00Z', price: 0 },
    { id: 12, user_id: 1, name: 'Budi Santoso', email: 'budi@email.com', phone: '081234567890', event_id: 8, payment_status: 'Gratis', checkin_status: 'Sudah', booked_at: '2026-03-01T00:00:00Z', price: 0 },
  ],

  stories: [
    { id: 1, title: "Recap: Gathering Bisnis Q2 2026", type: 'event', event_id: 8, community_id: null, category: 'Rekap Event', tags: ['bisnis', 'networking'], cover_image: '', content: "Gathering Bisnis Q2 2026 berjalan sukses dengan dihadiri 54 peserta dari berbagai latar belakang industri. Tema 'Scaling Your Business' menghadirkan tiga pembicara praktisi yang berbagi pengalaman nyata dalam mengembangkan usaha.\n\nSesi networking berlangsung hingga larut malam dengan antusiasme tinggi. Peserta bertukar kontak dan membuka peluang kolaborasi baru. D'Paragon Entrepreneur berencana menggelar sesi serupa di kuartal berikutnya.", author: 'Tim Redaksi D\'Paragon', published_at: '2026-04-16', status: 'published' },
    { id: 2, title: "Spotlight: D'Paragon Entrepreneur", type: 'community', event_id: null, community_id: 4, category: 'Komunitas', tags: ['bisnis', 'komunitas'], cover_image: '', content: "Forum networking D'Paragon Entrepreneur terus berkembang sejak berdiri. Dengan lebih dari 60 anggota aktif, komunitas ini menjadi salah satu yang paling dinamis di ekosistem D'Paragon.\n\nSetiap Jumat pertama, ruang sharing session dipenuhi diskusi soal strategi bisnis, peluang investasi, dan kolaborasi antar pelaku usaha. Jika Anda penghuni D'Paragon dan ingin memperluas jaringan bisnis, komunitas ini adalah pilihan tepat.", author: 'Tim Komunitas D\'Paragon', published_at: '2026-03-10', status: 'published' },
    { id: 3, title: "Tips Aktif & Produktif ala Penghuni D'Paragon", type: 'general', event_id: null, community_id: null, category: 'Lifestyle', tags: ['lifestyle', 'tips'], cover_image: '', content: "Gaya hidup aktif menjadi ciri khas penghuni D'Paragon. Mulai dari lari pagi bersama komunitas, sesi foto kreatif, hingga forum bisnis malam hari — semua bisa ditemukan di satu kawasan.\n\nBerikut tips agar tetap produktif: bergabunglah dengan minimal satu komunitas, ikut event bulanan, dan manfaatkan fasilitas komunal yang tersedia.", author: 'D\'Paragon Community', published_at: '2026-02-28', status: 'draft' },
    { id: 4, title: "Seru! 500+ Peserta Ikut Community Run D'Paragon 2026", type: 'general', event_id: null, community_id: null, category: 'Rekap Event', tags: ['lari', 'komunitas'], cover_image: '', content: "Acara Community Run D'Paragon 2026 yang berlangsung pada 15 Maret lalu menjadi bukti nyata semangat komunitas yang terus berkembang. Ratusan peserta dari berbagai kalangan hadir memeriahkan event tahunan ini.\n\nRute 5K dan 10K dirancang melewati landmark ikonik kawasan D'Paragon BSD, memberikan pengalaman yang berbeda dan menyenangkan bagi setiap peserta.", author: 'Tim Redaksi D\'Paragon', published_at: '2026-03-20', status: 'published' },
    { id: 5, title: "5 Komunitas Baru Bergabung di D'Paragon Community Hub", type: 'general', event_id: null, community_id: null, category: 'Komunitas', tags: ['komunitas', 'hub'], cover_image: '', content: "Pertumbuhan komunitas di lingkungan D'Paragon terus menunjukkan tren positif. Memasuki kuartal pertama 2026, lima komunitas baru resmi bergabung ke dalam ekosistem D'Paragon Community Hub.\n\nProses pendaftaran komunitas kini semakin mudah melalui fitur 'Pengajuan Komunitas' di website D'Paragon.", author: 'Tim Komunitas D\'Paragon', published_at: '2026-03-10', status: 'published' },
  ],

  reviews: [
    { id: 1, event_id: 4, user_id: 9, rating: 5, comment: "Event terbaik tahun ini! Pembicara relevan dan sesi networking sangat produktif. Pasti ikut lagi di sesi berikutnya.", status: 'approved', submitted_at: '2026-04-16T00:00:00Z' },
    { id: 2, event_id: 4, user_id: 10, rating: 4, comment: "Insight bisnis langsung applicable. Sesi panel-nya tajam dan diskusinya terbuka. Komunitas DParagon Entrepreneur emang beda!", status: 'approved', submitted_at: '2026-04-17T00:00:00Z' },
    { id: 3, event_id: 4, user_id: 11, rating: 5, comment: "Event paling berkesan tahun ini! Komunitas D'Paragon memang beda levelnya. Worth it banget hadir di sini.", status: 'pending', submitted_at: '2026-04-18T00:00:00Z' },
    { id: 4, event_id: 1, user_id: 2, rating: 4, comment: "Rutenya keren banget, melewati spot-spot terbaik kawasan D'Paragon! Tapi antrian di start agak panjang. Semoga next year lebih lancar.", status: 'pending', submitted_at: '2026-04-21T00:00:00Z' },
  ],

  banners: [
    { id: 501, type: 'story', info_id: 1, status: 'active', order: 0 },
    { id: 502, type: 'event', info_id: 1, status: 'active', order: 1 },
    { id: 503, type: 'community', info_id: 4, status: 'active', order: 2 },
  ],
};
